sudo: required
services:
- docker
before_install:
- docker build -t postql/tests -f ./server/Dockerfile.dev ./server
script:
- docker run -e CI=true -e USER_DATABASE -e LOGS_DATABASE -e JWT_SECRET  postql/tests
  npm run test
after_success:
- docker build -t postql/client ./client
- docker build -t postql/server ./server
- docker build -t postql/nginx ./nginx
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push postql/client
- docker push postql/server
- docker push postql/nginx
env:
  global:
  - secure: Co7QSDdbOqjfULB4wv9jeOSfG/kOqFnHhgKlLIXmBtMNlBwPYeg1OJtgQG1VAnWmAleMiCOPILyiDdcTZK5weB1TH8xdS+OYvfg+mEf0o+lYU5CxoX22Q61zc6AfEDJzYVV9asE802Gag0MIxwzPy/hiCnCqvgai0dEozfN9xVD489ujdmMtIPSnAe4QrSdLMr16E7Ccfd6hekvhv1LyJdwU3E2mjXBoqJLMsSMW2lK0/tW6/lkLc8W5HVm9BzM8L7DTmZH56+b1WA2KLib80KVfHjRZjsPd8HnMSICJJiA11I026JcxHIwlSvkyR6mHt3q02syy5qbyYZoer7KPYcMh3O8CUIj8fckpTy259WFL1f5BAS5c6PP45zZY37rshgnNPTkAq15cyHTWPRRxT7oirsIyp2U4Z8hPHld1mQ1ypMvpaPzrpjrJfu0d/TiOhO+6URomXpyVfcQ9vjL26PbvIMku5xWwhtgpk8a6XD3NNNlgtGMBwyZ1lTkH+F81BjtOaxVdLWRymnCeePDqVBUjqM+AxCAc6iPZyEeNiDDWBoQM1dPz29A+MMNL3DGic9FglbGDrSYrsqcxU5kS3Hr1sOlceFir6RCPOiCeIgDKCH7u0dWJtTT66B6mqRN84UCjUKHfsMerQDDF9y6wfBxuxg9iN1TGO/5P2FW1jFk=
  - secure: VqBAMVX0UgLXnO3vagPGqCIvqDmcUopYeqE4aY7D2WxqSbsH3SE813oBsp5omPXzbagBqKULGcFL+8neZZI4hF371orrkTPNnPGe6UC6H7ThaBSw+CRna0VneHqEeL98hRUajYouMrPGdp36fClfrmSsqmyLGH48HeZ97i08oOICfb4STVR533+t+7ono0SBOwSSAOYx89e1vrWkGi59q3Zi9z/Y6QWZRwxdIJlSi3+JS/iWkMJN1pu4vV1rfdXf/0t1uRdyZrBWR4i/tLnkBIewumhw/8NjFDxUYQlM83DvKZ08DRDKHoRrU1pqJ4Blq4B1/XLte7A5m0fkgxkqzLbE7LDvzfkwoj8qCMuVeL8id3EFxnRXbbRl4uphUdO95ogWMCBKQPOnwrOM4crjC2mz2aQwBXw7vxJx7T4+f667QMfmAjMkMc6x+sqXY2x7ercXaSAXntB9xmPVyKIkDPY3bKrmtCIMxv86S1IYHrHBnC9O4AJqtLbLsKixyIuTYUH2uSep1KxHpvG8EIIAeualRdoYshQ4JMlWC4PMnVoDrAxyZwtK8FV/eDH7EByGxkEpWs7o6vGu/kCLnn6JvY4ZLn2dN2w7ZAthLk/qD76h0xel3bMPRrYgGAi3YBvcAyk29Qq7S46eis8f544OOfB8HwUE4ljpO8NO5dkaW00=
  - secure: doFJdeY8EkatQFzywuXyBIsriZKQ4rNTh1/6bMupYPYLIbDHoZkfxOsnS2i54rVmpi6hqJlyjYvZfit4Y2gZeifC1ky/gIppFPeTMlR+cB5lS5t+d2lXllAE0XnGW5ViDItzi+be3jNYreHGeJZ0ARsbeWnKqGEg7AX8prs44CFSwEgOuTP3ggdu3/YX6GL8HK3BLKQ6WbeuXfel464LgyWzzaapITbSslGpautaxt1Z1FF1rZcfptv4/XO4HjrylcWigdtn5lwhRVz/nWVmfPZzeKFbb6xPci4ik4MoL5rmkX5Ef+Z9ST0uBz6kxXhDRf4ZikVpREv36FEeX2wwSMrwasdB8z4cksdCVt3DYSNLZ31io3GblGXY44f3lthnBsIm1unZTwmHfID9x3luBUrXn7FoMfs+fKKXWc8b0L/vQFDNPwkAo4QWJbdGpDwoSzCEJsLolnMWew5f98zGmL4+l35powk2QwIqycXXHPE4d2vmI8Jz5zywqkgrWCzzS8JhZVTdX3bzQaRPhsQAtOEMURukeI87J8UbsHobrMgyZkCNFx9mzOFTwglWg3rmk/ucG+jkMIjcqJdhGD6yTP9s6NtciutiRySUaYJmNhEfOt7r6ZPsnRZAiZb8LYjDwqaW6o4eLh0gY90wd4MvAyo0uHjo6/6FupAaby/cp2I=
