version: '3'
services:
  nginx:
    restart: always
    depends_on:
      - client
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 8080:80
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app